import { v4 as uuid } from "uuid";
import {
  uniqueNamesGenerator,
  adjectives,
  animals,
} from "unique-names-generator";

const capitalizedName = uniqueNamesGenerator({
  dictionaries: [adjectives, animals],
  style: "capital",
});

export const propertyList = [
  {
    _id: uuid(),
    name: { capitalizedName },
    price: 450,
    address: "New York",
    rooms: 2,
    type: "Ranch",
    image: "https://picsum.photos/id/193/250/150",
  },
  {
    _id: uuid(),
    name: { capitalizedName },
    price: 450,
    address: "New York",
    rooms: 5,
    type: "Cottage",
    image: "https://picsum.photos/id/194/250/150",
  },
  {
    _id: uuid(),
    name: { capitalizedName },
    price: 800,
    address: "New York",
    rooms: 3,
    type: "Cottage",
    image: "https://picsum.photos/id/195/250/150",
  },
  {
    _id: uuid(),
    name: { capitalizedName },
    price: 4000,
    address: "New York",
    rooms: 4,
    type: "Villa",
    image: "https://picsum.photos/id/196/250/150",
  },
  {
    _id: uuid(),
    name: { capitalizedName },
    price: 2200,
    address: "New York",
    rooms: 2,
    type: "Penthouse",
    image: "https://picsum.photos/id/197/250/150",
  },
  {
    _id: uuid(),
    name: { capitalizedName },
    price: 8500,
    address: "New York",
    rooms: 5,
    type: "Penthouse",
    image: "https://picsum.photos/id/19/250/150",
  },
  {
    _id: uuid(),
    name: { capitalizedName },
    price: 45000,
    address: "San Fransisco",
    rooms: 14,
    type: "Villa",
    image: "https://picsum.photos/id/13/250/150",
  },
  {
    _id: uuid(),
    name: { capitalizedName },
    price: 450,
    address: "San Fransisco",
    rooms: 2,
    type: "Ranch",
    image: "https://picsum.photos/id/144/250/150",
  },
  {
    _id: uuid(),
    name: { capitalizedName },
    price: 12000,
    address: "Miami",
    rooms: 6,
    type: "Cottage",
    image: "https://picsum.photos/id/199/250/150",
  },
  {
    _id: uuid(),
    name: { capitalizedName },
    price: 1000,
    address: "San Fransisco",
    rooms: 3,
    type: "Cottage",
    image: "https://picsum.photos/id/113/250/150",
  },
  {
    _id: uuid(),
    name: { capitalizedName },
    price: 200,
    address: "Texas",
    rooms: 2,
    type: "Cottage",
    image: "https://picsum.photos/id/93/250/150",
  },
  {
    _id: uuid(),
    name: { capitalizedName },
    price: 3100,
    address: "San Fransisco",
    rooms: 4,
    type: "Villa",
    image: "https://picsum.photos/id/43/250/150",
  },
  {
    _id: uuid(),
    name: { capitalizedName },
    price: 8500,
    address: "San Fransisco",
    rooms: 5,
    type: "Penthouse",
    image: "https://picsum.photos/id/122/250/150",
  },

  {
    _id: uuid(),
    name: { capitalizedName },
    price: 450,
    address: "Texas",
    rooms: 2,
    type: "Ranch",
    image: "https://picsum.photos/id/134/250/150",
  },
  {
    _id: uuid(),
    name: { capitalizedName },
    price: 1275,
    address: "Texas",
    rooms: 6,
    type: "Cottage",
    image: "https://picsum.photos/id/37/250/150",
  },
  {
    _id: uuid(),
    name: { capitalizedName },
    price: 1900,
    address: "Texas",
    rooms: 3,
    type: "Cottage",
    image: "https://picsum.photos/id/305/250/150",
  },
  {
    _id: uuid(),
    name: { capitalizedName },
    price: 4200,
    address: "Texas",
    rooms: 4,
    type: "Villa",
    image: "https://picsum.photos/id/133/250/150",
  },
  {
    _id: uuid(),
    name: { capitalizedName },
    price: 8500,
    address: "Texas",
    rooms: 5,
    type: "Penthouse",
    image: "https://picsum.photos/id/146/250/150",
  },
  {
    _id: uuid(),
    name: { capitalizedName },
    price: 420,
    address: "Texas",
    rooms: 5,
    type: "Penthouse",
    image: "https://picsum.photos/id/69/250/150",
  },

  {
    _id: uuid(),
    name: { capitalizedName },
    price: 450,
    address: "Miami",
    rooms: 2,
    type: "Ranch",
    image: "https://picsum.photos/id/73/250/150",
  },
  {
    _id: uuid(),
    name: { capitalizedName },
    price: 1999,
    address: "Miami",
    rooms: 3,
    type: "Cottage",
    image: "https://picsum.photos/id/83/250/150",
  },
  {
    _id: uuid(),
    name: { capitalizedName },
    price: 4500,
    address: "Miami",
    rooms: 4,
    type: "Villa",
    image: "https://picsum.photos/id/9/250/150",
  },
  {
    _id: uuid(),
    name: { capitalizedName },
    price: 8500,
    address: "Miami",
    rooms: 5,
    type: "Penthouse",
    image: "https://picsum.photos/id/1/250/150",
  },
  {
    _id: uuid(),
    name: { capitalizedName },
    price: 8500,
    address: "Miami",
    rooms: 5,
    type: "Villa",
    image: "https://picsum.photos/id/3/250/150",
  },
];
