import { v4 as uuid } from "uuid";
import {
  uniqueNamesGenerator,
  adjectives,
  animals,
} from "unique-names-generator";

const capitalizedName = uniqueNamesGenerator({
  dictionaries: [adjectives, animals],
  style: "capital",
});

export const propertyList = [
  {
    _id: uuid(),
    name: { capitalizedName },
    price: 450,
    address: "New York",
    rooms: 2,
    type: "Ranch",
    image: "https://picsum.photos/id/193/250/150",
  },
  {
    _id: uuid(),
    name: { capitalizedName },
    price: 450,
    address: "New York",
    rooms: 5,
    type: "Cottage",
    image: "https://picsum.photos/id/193/250/150",
  },
  {
    _id: uuid(),
    name: { capitalizedName },
    price: 1000,
    address: "New York",
    rooms: 3,
    type: "Cottage",
    image: "https://picsum.photos/id/193/250/150",
  },
  {
    _id: uuid(),
    name: { capitalizedName },
    price: 4000,
    address: "New York",
    rooms: 4,
    type: "Villa",
    image: "https://picsum.photos/id/193/250/150",
  },
  {
    _id: uuid(),
    name: { capitalizedName },
    price: 2200,
    address: "New York",
    rooms: 2,
    type: "Penthouse",
    image: "https://picsum.photos/id/193/250/150",
  },
  {
    _id: uuid(),
    name: { capitalizedName },
    price: 8500,
    address: "New York",
    rooms: 5,
    type: "Penthouse",
    image: "https://picsum.photos/id/193/250/150",
  },
  {
    _id: uuid(),
    name: { capitalizedName },
    price: 45000,
    address: "San Fransisco",
    rooms: 14,
    type: "Villa",
    image: "https://picsum.photos/id/193/250/150",
  },
  {
    _id: uuid(),
    name: { capitalizedName },
    price: 450,
    address: "San Fransisco",
    rooms: 2,
    type: "Ranch",
    image: "https://picsum.photos/id/193/250/150",
  },
  {
    _id: uuid(),
    name: { capitalizedName },
    price: 12000,
    address: "Miami",
    rooms: 6,
    type: "Cottage",
    image: "https://picsum.photos/id/193/250/150",
  },
  {
    _id: uuid(),
    name: { capitalizedName },
    price: 1000,
    address: "San Fransisco",
    rooms: 3,
    type: "Cottage",
    image: "https://picsum.photos/id/193/250/150",
  },
  {
    _id: uuid(),
    name: { capitalizedName },
    price: 200,
    address: "Texas",
    rooms: 2,
    type: "Cottage",
    image: "https://picsum.photos/id/193/250/150",
  },
  {
    _id: uuid(),
    name: { capitalizedName },
    price: 4000,
    address: "San Fransisco",
    rooms: 4,
    type: "Villa",
    image: "https://picsum.photos/id/193/250/150",
  },
  {
    _id: uuid(),
    name: { capitalizedName },
    price: 8500,
    address: "San Fransisco",
    rooms: 5,
    type: "Penthouse",
    image: "https://picsum.photos/id/193/250/150",
  },

  {
    _id: uuid(),
    name: { capitalizedName },
    price: 450,
    address: "Texas",
    rooms: 2,
    type: "Ranch",
    image: "https://picsum.photos/id/193/250/150",
  },
  {
    _id: uuid(),
    name: { capitalizedName },
    price: 1000,
    address: "Texas",
    rooms: 6,
    type: "Cottage",
    image: "https://picsum.photos/id/193/250/150",
  },
  {
    _id: uuid(),
    name: { capitalizedName },
    price: 1000,
    address: "Texas",
    rooms: 3,
    type: "Cottage",
    image: "https://picsum.photos/id/193/250/150",
  },
  {
    _id: uuid(),
    name: { capitalizedName },
    price: 4000,
    address: "Texas",
    rooms: 4,
    type: "Villa",
    image: "https://picsum.photos/id/193/250/150",
  },
  {
    _id: uuid(),
    name: { capitalizedName },
    price: 8500,
    address: "Texas",
    rooms: 5,
    type: "Penthouse",
    image: "https://picsum.photos/id/193/250/150",
  },
  {
    _id: uuid(),
    name: { capitalizedName },
    price: 420,
    address: "Texas",
    rooms: 5,
    type: "Penthouse",
    image: "https://picsum.photos/id/193/250/150",
  },

  {
    _id: uuid(),
    name: { capitalizedName },
    price: 450,
    address: "Miami",
    rooms: 2,
    type: "Ranch",
    image: "https://picsum.photos/id/193/250/150",
  },
  {
    _id: uuid(),
    name: { capitalizedName },
    price: 1000,
    address: "Miami",
    rooms: 3,
    type: "Cottage",
    image: "https://picsum.photos/id/193/250/150",
  },
  {
    _id: uuid(),
    name: { capitalizedName },
    price: 4000,
    address: "Miami",
    rooms: 4,
    type: "Villa",
    image: "https://picsum.photos/id/193/250/150",
  },
  {
    _id: uuid(),
    name: { capitalizedName },
    price: 8500,
    address: "Miami",
    rooms: 5,
    type: "Penthouse",
    image: "https://picsum.photos/id/193/250/150",
  },
  {
    _id: uuid(),
    name: { capitalizedName },
    price: 8500,
    address: "Miami",
    rooms: 5,
    type: "Villa",
    image: "https://picsum.photos/id/193/250/150",
  },
];
